.github/CODEOWNERS
.github/settings.yaml
.github/workflow/ci.yaml
go.mod

This adds the initial go mod, codeowners, and CI setup.
Fixes: #
I have:

Initial setup

---

.github/workflows/ci-checks.sh
Makefile
api/v1alpha1/zz_generated.deepcopy.go
go.mod

This makes sure we don't miss imports.
Fixes: #
I have:

Add checking for missing Go modules and import formatting:

---

smee/internal/ipxe/binary/file/script/build_and_pr.sh

remove changing directories in the iPXE build script.
Fixes: #
I have:

Fix iPXE CI build issue

---

.github/workflows/ipxe.yaml

Use default GH Actions token:

---

cmd/flag/flag.go
main.go

One clean up of the CLI Help output and one to add the bool type to all Flags in the CLI help.
Fixes: #
I have:

Cleans ups:

---

.gitignore
Dockerfile
backend/kube/kube.go
cmd/flag/smee.go
cmd/flag/tink_server.go
docker-compose.yaml
smee/smee.go

Small clean up and add Dockerfile and compose file.
Fixes: #
I have:

Clean up and Add Dockerfile and compose file:

---

config/crd/kustomization.yaml
docker-compose.yaml

This moves away from the service specific repos for CRDs.
Fixes: #
I have:

Point to tinkerbell/tinkerbell for CRD in docker compose:

---

README.md

Add few GitHub badges:

---

Dockerfile
Dockerfile.agent
Dockerfile.tinkerbell
agent/agent.go
agent/internal/transport/grpc/grpc.go
cmd/tinkerbell/cmd.go
cmd/tinkerbell/main.go
docker-compose.yaml
smee/internal/ipxe/script/ipxe.go
smee/internal/ipxe/script/ipxe_test.go
smee/internal/ipxe/script/static.go

Agent logic fixes; static `auto.ipxe` updates; start of multi platform container builds:

---

.github/workflows/ci.yaml
Makefile

This will push images to registry in GitHub Actions.
Fixes: #
I have:

Add container image buiding:

---

Makefile
config/crd/bases/tinkerbell.org_workflows.yaml
docker-compose.yaml
pkg/api/v1alpha1/tinkerbell/workflow.go
tink/controller/internal/workflow/hardware.go
tink/controller/internal/workflow/job.go
tink/controller/internal/workflow/job_test.go
tink/controller/internal/workflow/pre.go
tink/controller/internal/workflow/pre_test.go
tink/controller/internal/workflow/reconciler.go

Update the API spec for the `iso` bootMode. 
Use SetConditionIfDifferent everywhere possible. This is needed so as to not overwhelm the Kubernetes event system if failures grow.
Fixes: #
I have:

[tink-controller] Controller update; API change for BootMode `iso` to `isoboot` 

---

cmd/tinkerbell/backend.go
cmd/tinkerbell/cmd.go
cmd/tinkerbell/flag/smee.go
cmd/tinkerbell/main.go
pkg/backend/kube/kube.go
pkg/proto/workflow.proto
smee/internal/ipxe/http/http.go
smee/smee.go
tink/agent/agent.go
tink/agent/internal/transport/grpc/grpc.go
tootles/internal/frontend/ec2/frontend.go
tootles/internal/middleware/middleware.go
tootles/internal/xff/xff.go

The publicIP was not being used properly when set. There are also some fixes needed for running in a Kubernetes cluster.
Fixes: #
I have:

Fixes for publicIP use and running in cluster

---

config/crd/bases/tinkerbell.org_workflows.yaml
pkg/api/v1alpha1/tinkerbell/workflow.go
tink/controller/internal/workflow/post.go
tink/controller/internal/workflow/pre.go

Instead of removing the `iso` bootMode, add an additional one of `isoboot`. This will keep existing users working and provide a deprecation path.
Fixes: #
I have:

Don't break the Workflow API:

---

.github/workflows/ci.yaml

This will be needed when the kube-apiserver embedding lands.
Fixes: #
I have:

Add GitHub Actions Go caching:

---

.github/workflows/ci.yaml

As we now use a cache in CI test, make sure we always run tests.
Fixes: #
I have:

Always run tests in CI:

---

.github/workflows/ci.yaml

Fixes conflicts with restoring the cache for builds and tests.
Fixes: #
I have:

Fix caching errors in CI:

---

Makefile
secondstar/internal/handler.go
secondstar/internal/key_test.go
secondstar/internal/multi.go
secondstar/internal/multi_test.go
secondstar/internal/store.go
secondstar/internal/store_test.go
secondstar/secondstar.go
secondstar/secondstar_test.go

Split the initial session and additional session handling functions. Change the State connected/additional sessions field to use Go stdlib thread safe types. Add a basic amount of testing.
Fixes: #
I have:

[secondstar] Refactor concurrent session handling:

---

.github/workflows/ci.yaml
Makefile
README.md

Add badges to readme; upload to codecov:

---

.github/codecov.yml
README.md

Make the codecov informational so it doesn't fail the check. Have it ignore generate code files.
Fixes: #
I have:

Add codecov config file:

---

helm/tinkerbell/templates/deployment.yml
helm/tinkerbell/templates/hookos/_functions.tpl
helm/tinkerbell/templates/hookos/service.yaml
helm/tinkerbell/templates/role.yaml
helm/tinkerbell/values.yaml

This helps simplify what is needed for the helm install command.
Fixes: #
I have:

[helm chart] Simplify required values for HookOS artifacts location:

---

.github/codecov.yml
cmd/tinkerbell/cmd.go
cmd/tinkerbell/flag/etcd.go
cmd/tinkerbell/flag/rufio.go
cmd/tinkerbell/flag/secondstar.go
cmd/tinkerbell/flag/smee.go
cmd/tinkerbell/flag/tink_controller.go
cmd/tinkerbell/flag/tink_server.go
cmd/tinkerbell/flag/tootles.go
secondstar/secondstar.go

This helps to debug individual services when external logging tools are available.
Fixes: #38 
I have:

Log level per service

---

.github/dependabot.yml

Add dependabot config:

---

.github/dependabot.yml

Remove duplicate entry

---

.github/mergify.yml

Add mergify config

---

go.mod

Update versions that have the `replace` directive defined:

---

.github/workflows/ci.yaml

The check depth needs to be everything so that tags will be present.
Fixes: #
I have:

[CI] Make sure tags are in the git history:

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
Makefile

VERSION is calculated via ./script/version/main.go and allows all images and helm charts to use the
exact same version.
Fixes: #
I have:

Update Container image tags to use VERSION:

---

README.md

Sort sections alphabetically

---

docs/ADOPTERS.md

We (Konstruct) use Tinkerbell to orchestrate bare metal server deployment. 
Fixes: #
I have:

feat: add Colony as adopter

---

docs/technical/AUTO_ENROLLMENT.md

The auto enrollment doc link to the Quamina patterns was broken.
Fixes: #
I have:

Fix bad link:

---

helm/tinkerbell/README.md
helm/tinkerbell/templates/deployment.yml
helm/tinkerbell/values.yaml

Add a basic readme for the Helm chart.
Fixes: #
I have:

Helm chart readme

---

docs/technical/AUTO_DISCOVERY.md

Workflows have nothing to do with auto discovery.
Fixes: #
I have:

Fix auto discovery doc:

---

docs/technical/AUTO_DISCOVERY.md
docs/technical/AUTO_ENROLLMENT.md
docs/technical/DHCP_BOOT_MODES.md

Update and add docs.
Fixes: #
I have:

Update auto docs; add dhcp boot modes doc

---

helm/tinkerbell/templates/deployment.yml

This was previously related to a DHCP relay. This is not the case anymore. Removing "relay" to remove any misunderstanding.
Fixes: #
I have:

rename init container:

---

helm/tinkerbell/templates/hookos/pvc.yaml

Remove hard coded name for PVC

---

crd/crd.go

When updating a CRD, some metadata fields are required.
Fixes: #
I have:

Handle CRD updates properly:

---

helm/tinkerbell/values.yaml

Default to latest released HookOS:

---

smee/internal/syslog/receiver.go
smee/internal/syslog/receiver_test.go

Add unit tests for syslog receiver:

---

tootles/internal/frontend/hack/hack.go

Updates /metadata endpoint in tootles, it now returns error 500 with description of missing hardware.
Fixes: #231
Standard testing [make test] 
I have:

fix: update /metadata endpoint for no corresponding hardware object (#231)

---

tink/agent/internal/runtime/docker/registry.go
tink/agent/internal/runtime/docker/registry_test.go

This library has no third-party dependencies and handles all the necessary tasks.
Fixes: #
I have:

Use github.com/distribution/reference for auth checking:

---

helm/tinkerbell/templates/deployment.yml
helm/tinkerbell/values.yaml

Plumb through iPXE mac addr injection in helm chart

---

smee/smee.go

These are already included in the cmd pkg.
Fixes: #
I have:

Remove redundant log values:

---

smee/internal/ipxe/binary/file/script/build_ipxe.sh

This allows a single location to control the extra version format.
Fixes: #
I have:

Create the iPXE extra version in one place:

---

docs/technical/smee/DHCP.md

Update iPXE script, auto.ipxe, URI

---

.github/workflows/ci.yaml

We shouldn't publish a helm chart until the images in that chart are available in the registry.
Fixes: #
I have:

Require successful container image push:
