- README.md
- cmd/tinkerbell/cmd.go
- cmd/tinkerbell/flag/rufio.go
- cmd/tinkerbell/flag/tink_controller.go
- rufio/rufio.go
- tink/controller/controller.go
Rufio and Tink controller need to create lease objects for leader election. When Tinkerbell is run outside of a Kubernetes cluster this namespace must be explicitly defined. When Tinkerbell is run in cluster, if a namespace is not define, the namespace where Tinkerbell is running is used.
Also, in the logging output, trim the source file name for 3rd party packages.
Update the readme.
Fixes: #
I have:
> Update Readme, add default namespace for leader election

- docker-compose.yaml
- tink/controller/internal/workflow/reconciler.go
Limit updating of conditions. Only update conditions when they are different from existing conditions on an object. This is needed so as to not overwhelm the Kubernetes event system if failures grow.
Fixes: #
I have:
> [tink controller] Workflow reconcile update

- cmd/tinkerbell/cmd.go
- cmd/tinkerbell/flag/global.go
- cmd/tinkerbell/flag/secondstar.go
- go.mod
- go.sum
- pkg/backend/kube/index.go
- pkg/backend/kube/kube.go
- pkg/backend/kube/secondstar.go
- pkg/data/bmc.go
- rufio/internal/controller/machine.go
- rufio/rufio.go
- secondstar/internal/handler.go
- secondstar/internal/key.go
- secondstar/internal/multi.go
- secondstar/secondstar.go
This implements a new feature for getting access to a serial-over-lan interface with SSH. Serial over SSH. The "service" or code is organized into a package name `secondstar`, as in the location of Neverland in the modern Peter Pan story. "_Second star to the right and straight on 'til morning_".
Fixes: #
I have:
> Serial over SSH

- .github/workflows/ci.yaml
- apiserver/apiserver.go
This keeps this isolated to when embedding is used. Also, enabled a build cache for binary builds.
Fixes: #
I have:
> Add embedded build tags to apiserver pkg: add cache for binaries:

- Makefile
Apple's own tools are either not-GNU or old. Detect Darwin and Homebrew, stop if not using 4.x make, recommend `gmake`; prepend GNU versions of tools to `PATH`.
> Make it easy to build under MacOS (with brew)

- helm/tinkerbell/templates/deployment.yml
- helm/tinkerbell/values.yaml
Quick way. One day we could refactor the podSpec into a separate helper and re-use common parts across split deployment/daemonset .yaml templates, but again, most shared settings are already under the "deployment" key.
- helm/tinkerbell: allow turning the Deployment into a Daemonset
- helm/tinkerbell: add nodeSelector
> helm/tinkerbell: allow turning the Deployment into a Daemonset

- helm/tinkerbell/templates/deployment.yml
- helm/tinkerbell/values.yaml
This plums through configuring kernel parameters for the iPXE `auto.ipxe` script. It handles appending the Tink Agent container image to any specified parameters.
Fixes: #
I have:
> [HELM CHART] Make kernel parameters configurable:

- .github/release.yml
- .github/workflows/release.yaml
We use a crane GitHub Action instead of using docker/metadata-action because the helm chart uses a tag of `vX.Y.Z-<sha>` and with docker/metadata-action I couldn't find a way to get this tag format for the existing helm chart image.
Fixes: #
I have:
> Add release GitHub Actions workflow and release template:

- .github/workflows/release.yaml
Using `${{ github.repository }}` caused the `IMAGE` variable to be `ghcr.io/tinkerbell/tinkerbell`. In the job matrix this caused the names to be `ghcr.io/tinkerbell/tinkerbell/tinkerbell` and `ghcr.io/tinkerbell/tinkerbell/tink-agent`, etc.
Fixes: #
I have:
> Fix image base for GHA release:

- helm/tinkerbell/templates/hookos/download-configmap.yaml
- helm/tinkerbell/templates/hookos/pvc.yaml
- helm/tinkerbell/templates/leader-election-role-binding.yaml
- helm/tinkerbell/templates/leader-election-role.yaml
- helm/tinkerbell/templates/role-binding.yaml
- helm/tinkerbell/templates/service-account.yaml
- helm/tinkerbell/templates/service.yaml
A few hardcoded `"tinkerbell"` namespace in the Helm Chart. Replace with Release's namespace. Standardize on the quote.
> helm/tinkerbell: fix namespace references

- smee/internal/syslog/message.go
With the Agent now logging attributes at start up the log message with the attributes was not being captured properly in the syslog receiver and the attributes log line was not logged at all. Increasing the buffer allows for larger log lines send over syslog to get logged properly.
Fixes: #
I have:
> Increase syslog message buffer to 32kb:

- helm/tinkerbell/templates/deployment.yml
- helm/tinkerbell/values.yaml
This is needed if users don't want Tinkerbell to touch any existing CRDs.
Fixes: #
I have:
> Add env var for enable/disable CRD migrations:

- .github/workflows/ipxe.yaml
- smee/internal/ipxe/binary/file/script/build_and_pr.sh
- smee/internal/ipxe/binary/file/script/shell.nix
- so forks can get GHA ipxe builds going
- and not on every push
- remove `gh` binary
> small GHA/CI fixes for iPXE building

- tink/agent/agent.go
- tink/agent/internal/transport/grpc/error.go
- tink/agent/internal/transport/grpc/grpc.go
Logging all errors generically when reading/retrieving actions adds noise to the logs and with high numbers of Agents would cause way too much noise. Also, the error logs can potentially confuse users about actual errors vs just no Workflow is available at the moment. This logs only when the error is not an error related to a Workflows not available.
Fixes: #
I have:
> Quieter Agent logging:

- helm/tinkerbell/templates/service.yaml
This PR removes the duplicate `type` from the Service definition
Fixes: #159 
Fixes a bug, no additional steps are required.
I have:
> fix: remove duplicate `type`

- docker-compose.yaml
Use the env var name that Tinkerbell uses instead of renaming it. This obfuscation is not needed and requires additional understanding. Using the same as the Tinkerbell CLI removes this required understanding.
Fixes: #
I have:
> Update docker compose:

- helm/tinkerbell/templates/role.yaml
This is needed so that Tink Server can read the WorkflowRuleSets. Updated the formatting of all ClusterRole rules so that they use the same yaml formatting.
Fixes: #
I have:
> Add WorkflowRuleSets ClusterRole:

- tink/agent/agent.go
- tink/agent/internal/transport/grpc/grpc.go
- tink/agent/internal/transport/grpc/grpc_test.go
- tink/server/internal/grpc/grpc.go
Having retries in both tink-server and tink-agent caused noticeable delays in Workflow Actions running. With retries in tink-server only the delays disappeared. Benchmarking showed improved performance as well. A rudimentary benchmark showed over 1000 concurrent Agents performed fine. This is a not an official benchmark as the backing Kubernetes cluster plays a significant part in the performance and the benchmark was done with a local k3d cluster.
Fixes: #
I have:
> Move retries to tink-server:

- pkg/backend/kube/kube_test.go
- pkg/backend/kube/secondstar.go
- pkg/backend/kube/smee.go
- pkg/backend/kube/tootles.go
- smee/internal/dhcp/handler/proxy/proxy.go
This is needed because GetByMac and GetByIP both return data.DHCP and data.Netboot, but the DHCP proxy handler in Smee only needs data.Netboot. By only doing validation, the proxy handler functions properly.
Fixes: #197 
I have:
> Validate DHCP fields instead of requiring them:

- helm/tinkerbell/templates/hookos/deployment.yaml
- helm/tinkerbell/templates/hookos/download-configmap.yaml
- helm/tinkerbell/values.yaml
When the 6.6 kernel is specified for download, this script renames `initramfs-latest-lts-` to `initramfs-` and `vmlinuz-latest-lts-` to `vmlinuz-`, ensuring they are named as expected by the `auto.ipxe` script.
Fixes: #
I have:
> Rename HookOS 6.6 kernel and initramfs after downloading:

- cmd/tinkerbell/flag/smee.go
- smee/smee.go
This was hardcoded to true. This allows enabling/disabling the sending of netboot options in all DHCP handlers. This only makes sense when using the "reservation" handler/dhcp mode.
Even with the reservation mode/handler, disabling netboot options means that the user must bring their own proxyDHCP service. This has only been reported as needed when netbooting Raspberry PI SBCs because their firmware bootloaders don't natively work with iPXE.
Fixes: #
I have:
> Plum through enabling/disabling netboot:

- docs/technical/smee/DHCP.md
By default, the iPXE script is delivered by an HTTP server listening on port 7171, not the default port 80, so the port needs to be provided in the bootfile name send to the host.
A very small docs fix. In the examples on how to configure DHCP servers for delivering the iPXE script, the HTTP URLs don't contain the default `7171` port used when deploying Tinkerbell via the Helm chart, meaning hosts trying to use those examples would not be able to fetch the file.
I've not raised an issue for this.
Fixes: #
This is a docs change, revealed to me by hammering onto a dnsmasq config and staring at tcpdump output for a long long time before realising my DHCP setup was fine, I was just missing a port in the HTTP URL. 
No changes required from users. Impact should be a lot of time saved staring at …
> Add port to HTTP filename in DHCP examples

- api/v1alpha1/tinkerbell/hardware.go
- cmd/tinkerbell/flag/tink_server.go
- crd/bases/tinkerbell.org_hardware.yaml
- docs/technical/AUTO_DISCOVERY.md
- docs/technical/AUTO_ENROLLMENT.md
- pkg/backend/kube/error.go
- pkg/backend/kube/index.go
- pkg/backend/kube/tink_server.go
- smee/internal/ipxe/script/auto_test.go
- smee/internal/ipxe/script/hook.go
- tink/server/internal/grpc/discovery.go
- tink/server/internal/grpc/discovery_test.go
- tink/server/internal/grpc/kube_test.go
Discovering Hardware objects in cluster by name is problematic. Once a Hardware object is created, renaming it will cause a new one to be created. Then there will be issues with network booting as there will be more than one Hardware object and network booting won't occur.
To resolve this, an `agentID` field in the Hardware spec has been added and is used when looking up Hardware. This allows the creation of a Hardware object as part of the discovery process with the name `discovery-*`, and then users can rename these objects as needed.
Fixes: #
I have:
> Refactor Auto Discovery:

- cmd/tinkerbell/cmd.go
Smee supports OTEL but does not inherit from the global to be set.
Make OTEL configs effective for Smee.
> smee: pass otel config from global

- helm/tinkerbell/templates/hookos/deployment.yaml
This will trigger the HookOS deployment rollout when the HookOS download script changes. Same as what is currently done for the nginx config map.
Fixes: #
I have:
> Add checksum annotation for HookOS download script:

- .github/mergify.yml
- Makefile
- smee/internal/syslog/receiver.go
Fix panic on closed channel. This resolves a panic when the context is canceled and syslog messages are still being received.
Remove mergify speculative checks . This increases the merge time significantly because a new draft PR is opened for each PR, and all the tests must run. This is new behavior from Mergify, and I don't want it right now.
Fixes: #
I have:
> Fix syslog panic; Remove mergify speculative checks:

- cmd/tinkerbell/backend.go
- cmd/tinkerbell/cmd.go
- cmd/tinkerbell/flag/global.go
- helm/tinkerbell/templates/deployment.yml
- helm/tinkerbell/values.yaml
- pkg/backend/kube/kube.go
This allows configuring the kube backend's QPS and burst values. Needed for performance tuning of the controllers.
Fixes: #
I have:
> Make QPS and burst configurable:

- tink/agent/internal/attribute/attribute.go
while testing inside VMs, the auto-discovery feature of the tink-agent discovers disks /dev/ram{1..15} and /dev/nbd{0..15}. This change filters those out and prefers block devices which have a controllerType which isnt Loop or Unknown
This was found on HookOS 0.10.0-build-196.
I'm unsure if *all* block devices are going to be discovered 
Fixes: #
At least in my lab, on VMs and limited hardware types, this still correctly detects block devices which have an actual vendor reported from the device, and does not add every single "block" device to `spec.disks` in the generated `Hardware` object.
~The underlying `ghw` package reads from `/sys/block/<dev>/device/vendor`, and if the file doesn't exist will default to `"unknown"`~ [seen here](https://github.com/jaypipes/ghw/blob/v0.17.0/pkg/block/b …
> Tink Agent: filter out block devices with unknown controller type

- api/v1alpha1/tinkerbell/workflow.go
- crd/bases/tinkerbell.org_workflows.yaml
- tink/controller/internal/workflow/reconciler.go
- tink/controller/internal/workflow/reconciler_test.go
There are no breaking changes in this PR. This fixes a typo in the Workflow status API: `templateRending` -> `templateRendering`. This also implements multi-task, multi-agent Workflows. The example below shows a Template with 2 tasks that are assigned to 2 different Agents.
```yaml
apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
name: multi-agent
spec:
data: |
name: multi-agent
global_timeout: 90
tasks:
- name: "first task"
worker: "{{.agent2}}"
actions:
- name: "action 1"
image: alpine
timeout: 60
command: ["sleep", "4"]
- name: "second task"
worker: "{{.agent2}}"
actions:
- name: "action 1"
image: alpine
timeout: 60
command: ["sleep", "4"]
```
Here's the corresponding Workflow:
```yaml
apiVersion: "tinkerbell.org/v1alpha1"
kind: Workflow
metadata:
name: multi-agent
spec: …
```
> Implement multi-task multi-agent functionality in Workflows

- cmd/tinkerbell/flag/smee.go
The `--ipxe-binary-inject-mac-addr-format` and `--ipxe-override-arch-mapping` flags didn't handle the empty string case and caused the Helm chart to fail to deploy. This resolves that.
Fixes: #
I have:
> Handle the empty string case for new CLI flags:

- Dockerfile.agent
This allows TLS certs from publicly trusted CAs to work when the Agent uses TLS to connect to the Tink Server. This adds < 1mb of space to the container image. It doesn't solve the issue of custom CAs or self-signed certs.
Fixes: #
Manually tested.
I have:
> Add CA certificates to Agent container image:

- cmd/tinkerbell/cmd.go
- cmd/tinkerbell/flag/global.go
- cmd/tinkerbell/flag/smee.go
- cmd/tinkerbell/flag/tink_server.go
- cmd/tinkerbell/flag/tootles.go
- helm/tinkerbell/templates/deployment.yml
- helm/tinkerbell/values.yaml
- secondstar/secondstar.go
- smee/internal/ipxe/http/middleware.go
This makes it simpler and easier to specify a bind address that all services will use instead of the previous method of having to set CLI flags or Env vars for all services (9 bind addrs).
Fixes: #
I have:
> Add Global bind address

- pkg/flag/netip/netip.go
- pkg/flag/netip/netip_test.go
This makes it so that the default value of an "invalid IP" is an empty string. This improves the CLI help menu.
Fixes: #
I have:
> Add String method to netip.Addr:

- helm/tinkerbell/templates/hookos/deployment.yaml
- helm/tinkerbell/templates/hookos/service.yaml
- helm/tinkerbell/values.yaml
Tinkerbell can be configured to use hostNetwork in cases where a load-balancer isn't available, but hookos does not have this ability.  Nodeport could work, but would require the user to manually configure the service port number in values.yaml and then update the artifactsFileServer to use the same port.  This will simplify things for users without load-balancers because they can re-use the `7173` port.
Fixes: #
For my use case, I'm doing some testing with a single node cluster and a qemu VM similar to the metal3 quick start guide (https://book.metal3.io/quick-start).  I was able to test this by patching hookos `kubectl edit deploy hookos` and adding the `hostNetwork: true` configuration.  After doing this I was able to install an OS no the vm.  Wanted to share this solution so others …
> Helm: hookos hostnetwork should be configurable like tinkerbell

- .github/mergify.yml
This is needed because the GitHub branch protection setting `Require branches to be up to date before merging` is not compatible with draft PR checks in Mergify.
Fixes: #
I have:
> Enable Mergify in-place checks:
